<a href="https://colab.research.google.com/github/Bibekbishwas/labfpp1/blob/main/Assignment_2_and_3_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - 2
# Execute and explain 10 most used commands in numpy 
# and 5 most used commands in Pandas

**Numpy**

1. array
2. empty
3. zeros
4. ones
5. vstack
6. hstack
7. " Indexing "
8. " Slicing "
9.  hape
10. Reshape
11. " Broadcasting "

** Pandas

1. DataFrame, Series
2. head
3. describe
4. loc,iloc
5. read_csv

# Assignment - 3
# Compute the following with and without using libraries (numpy, scipy)       and interpret the computed values

1. Variance
2. Standard deviation
3. Covariance and Covariance Matrix
4. Correlation Coefficient and Correlation Matrix

# Execute the following Normalization methods and comment about them

5. Min-Max normalization
6. Standard Normlaization

# Compute different types of distances between two points

7. Euclidean distance
8. Manhattan distance
9. Chebyshev distance

# Advanced Question
10. Explain Mahalanobis distance.


In [8]:
import numpy as np

# 1D array 
x = [7.8, 8.2, 8.7, 9.2, 9.5] 
y = [3, 3.2, 3.8, 4.1, 9.4] 
print("X : ", x) 
print("X : ", x) 
print("var of x : ", np.var(x)) 
print("var of y : ", np.var(y))

print("\nvar of x : ", np.var(x, dtype = np.float32)) 
print("\nvar of y : ", np.var(y, dtype = np.float32))
print("\nvar of x : ", np.var(x, dtype = np.float64))
print("\nvar of y : ", np.var(y, dtype = np.float64))

X :  [7.8, 8.2, 8.7, 9.2, 9.5]
X :  [7.8, 8.2, 8.7, 9.2, 9.5]
var of x :  0.38960000000000006
var of y :  5.6800000000000015

var of x :  0.38959998

var of y :  5.68

var of x :  0.38960000000000006

var of y :  5.6800000000000015


In [9]:
import numpy as np

x = [7.8, 8.2, 8.7, 9.2, 9.5] 
y = [3, 3.2, 3.8, 4.1, 9.4]
#find out covariance with respect columns
cov_mat= np.stack((x , y ), axis=0)
print(np.cov(cov_mat))

[[0.487 1.435]
 [1.435 7.1  ]]


In [ ]:
print(A.shape)

(6,)


In [ ]:
A[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
B = A[:,np.newaxis]
print(B.shape)

(6, 1)


In [ ]:
np.transpose(B).shape

(1, 6)

In [ ]:
np.transpose(A).shape

(6,)

In [10]:
 import numpy as np

x = [7.8, 8.2, 8.7, 9.2, 9.5] 
y = [3, 3.2, 3.8, 4.1, 9.4]
#find out covariance with respect columns
cov_mat= np.stack((x , y ), axis=0)
print(np.cov(cov_mat))
r=np.corrcoef(x,y)
print(r)

[[0.487 1.435]
 [1.435 7.1  ]]
[[1.         0.77171732]
 [0.77171732 1.        ]]
